#pragma once

#include <string>
#include <unordered_map>
#include "CutsceneMM_Commands.h"

#define ENUM_TO_STRING(name)                                                                       \
	{                                                                                              \
		(uint32_t) CutsceneMM_CommandType::name, #name                                                 \
	}

const std::unordered_map<uint32_t, std::string> csMMEnumNameToString = {
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_100), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_101),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_102), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_103),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_104), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_105),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_106), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_107),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_108), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_109),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_110), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_111),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_112), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_113),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_114), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_115),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_116), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_117),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_118), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_119),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_120), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_121),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_122), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_123),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_124), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_125),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_126), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_127),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_128), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_129),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_130), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_131),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_132), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_133),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_134), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_135),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_136), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_137),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_138), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_139),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_140), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_141),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_142), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_143),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_144), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_145),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_146), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_147),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_148), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_149),
	ENUM_TO_STRING(CS_CMD_PLAYER_CUE),    ENUM_TO_STRING(CS_CMD_ACTOR_CUE_201),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_450), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_451),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_452), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_453),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_454), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_455),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_456), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_457),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_458), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_459),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_460), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_461),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_462), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_463),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_464), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_465),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_466), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_467),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_468), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_469),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_470), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_471),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_472), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_473),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_474), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_475),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_476), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_477),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_478), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_479),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_480), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_481),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_482), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_483),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_484), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_485),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_486), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_487),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_488), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_489),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_490), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_491),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_492), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_493),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_494), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_495),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_496), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_497),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_498), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_499),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_500), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_501),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_502), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_503),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_504), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_SOTCS),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_506), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_507),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_508), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_509),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_510), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_511),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_512), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_513),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_514), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_515),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_516), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_517),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_518), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_519),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_520), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_521),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_522), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_523),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_524), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_525),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_526), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_527),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_528), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_529),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_530), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_531),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_532), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_533),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_534), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_535),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_536), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_537),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_538), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_539),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_540), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_541),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_542), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_543),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_544), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_545),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_546), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_547),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_548), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_549),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_550), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_551),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_552), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_553),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_554), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_555),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_556), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_557),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_558), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_559),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_560), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_561),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_562), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_563),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_564), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_565),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_566), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_567),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_568), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_569),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_570), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_571),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_572), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_573),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_574), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_575),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_576), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_577),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_578), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_579),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_580), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_581),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_582), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_583),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_584), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_585),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_586), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_587),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_588), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_589),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_590), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_591),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_592), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_593),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_594), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_595),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_596), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_597),
	ENUM_TO_STRING(CS_CMD_ACTOR_CUE_598), ENUM_TO_STRING(CS_CMD_ACTOR_CUE_599),
};

#undef ENUM_TO_STRING

// see
// https://github.com/zeldaret/mm/blob/0c7b90cf97f26483c8b6a98ae099a295f61e72ab/include/z64cutscene.h#L109-118
const std::string csMMModifySeqTypes[] = {
	"CS_MOD_SEQ_0",      "CS_MOD_SEQ_1",      "CS_MOD_SEQ_2",     "CS_MOD_AMBIENCE_0",
	"CS_MOD_AMBIENCE_1", "CS_MOD_AMBIENCE_2", "CS_MOD_SEQ_STORE", "CS_MOD_SEQ_RESTORE",
};

// see
// https://github.com/zeldaret/mm/blob/0c7b90cf97f26483c8b6a98ae099a295f61e72ab/include/z64cutscene.h#L143-155
const std::string csMMCreditsSceneTypes[] = {
	"CS_CREDITS_DESTINATION", "CS_CREDITS_MASK_KAMARO",  "CS_CREDITS_MASK_GREAT_FAIRY",
	"CS_CREDITS_MASK_ROMANI", "CS_CREDITS_MASK_BLAST",   "CS_CREDITS_MASK_CIRCUS_LEADER",
	"CS_CREDITS_MASK_BREMEN", "CS_CREDITS_IKANA",        "CS_CREDITS_MASK_COUPLE",
	"CS_CREDITS_MASK_BUNNY",  "CS_CREDITS_MASK_POSTMAN",
};

// see
// https://github.com/zeldaret/mm/blob/0c7b90cf97f26483c8b6a98ae099a295f61e72ab/include/z64cutscene.h#L198-212
const std::string csMMTransitionTypes[] = {
	"CS_TRANS_GRAY_FILL_IN",   "CS_TRANS_BLUE_FILL_IN",  "CS_TRANS_RED_FILL_OUT",
	"CS_TRANS_GREEN_FILL_OUT", "CS_TRANS_GRAY_FILL_OUT", "CS_TRANS_BLUE_FILL_OUT",
	"CS_TRANS_RED_FILL_IN",    "CS_TRANS_GREEN_FILL_IN", "CS_TRANS_TRIGGER_INSTANCE",
	"CS_TRANS_BLACK_FILL_OUT", "CS_TRANS_BLACK_FILL_IN", "CS_TRANS_GRAY_TO_BLACK",
	"CS_TRANS_BLACK_TO_GRAY",
};

// see
// https://github.com/zeldaret/mm/blob/0c7b90cf97f26483c8b6a98ae099a295f61e72ab/include/z64cutscene.h#L226-234
const std::string csMMTextypes[] = {
	"CS_TEXT_TYPE_NONE",
	"CS_TEXT_TYPE_DEFAULT",
	"CS_TEXT_TYPE_1",
	"CS_TEXT_OCARINA_ACTION",
	"CS_TEXT_TYPE_3",
	"CS_TEXT_TYPE_BOSSES_REMAINS",
	"CS_TEXT_TYPE_ALL_NORMAL_MASKS",
};

// see
// https://github.com/zeldaret/mm/blob/0c7b90cf97f26483c8b6a98ae099a295f61e72ab/include/z64cutscene.h#L532-574
const std::string csMMMiscTypes[] = {
	"CS_MISC_UNIMPLEMENTED_0",
	"CS_MISC_RAIN",
	"CS_MISC_LIGHTNING",
	"CS_MISC_LIFT_FOG",
	"CS_MISC_CLOUDY_SKY",
	"CS_MISC_STOP_CUTSCENE",
	"CS_MISC_UNIMPLEMENTED_6",
	"CS_MISC_SHOW_TITLE_CARD",
	"CS_MISC_EARTHQUAKE_MEDIUM",
	"CS_MISC_EARTHQUAKE_STOP",
	"CS_MISC_VISMONO_BLACK_AND_WHITE",
	"CS_MISC_VISMONO_SEPIA",
	"CS_MISC_HIDE_ROOM",
	"CS_MISC_RED_PULSATING_LIGHTS",
	"CS_MISC_HALT_ALL_ACTORS",
	"CS_MISC_RESUME_ALL_ACTORS",
	"CS_MISC_SANDSTORM_FILL",
	"CS_MISC_SUNSSONG_START",
	"CS_MISC_FREEZE_TIME",
	"CS_MISC_LONG_SCARECROW_SONG",
	"CS_MISC_SET_CSFLAG_3",
	"CS_MISC_SET_CSFLAG_4",
	"CS_MISC_PLAYER_FORM_DEKU",
	"CS_MISC_ENABLE_PLAYER_REFLECTION",
	"CS_MISC_DISABLE_PLAYER_REFLECTION",
	"CS_MISC_PLAYER_FORM_HUMAN",
	"CS_MISC_EARTHQUAKE_STRONG",
	"CS_MISC_DEST_MOON_CRASH_FIRE_WALL",
	"CS_MISC_MOON_CRASH_SKYBOX",
	"CS_MISC_PLAYER_FORM_RESTORED",
	"CS_MISC_DISABLE_PLAYER_CSMODE_START_POS",
	"CS_MISC_ENABLE_PLAYER_CSMODE_START_POS",
	"CS_MISC_UNIMPLEMENTED_20",
	"CS_MISC_SAVE_ENTER_CLOCK_TOWN",
	"CS_MISC_RESET_SAVE_FROM_MOON_CRASH",
	"CS_MISC_TIME_ADVANCE",
	"CS_MISC_EARTHQUAKE_WEAK",
	"CS_MISC_UNIMPLEMENTED_25",
	"CS_MISC_DAWN_OF_A_NEW_DAY",
	"CS_MISC_PLAYER_FORM_ZORA",
	"CS_MISC_FINALE",
};
